---GENERAL QUERIES TO TEST THE DATA USABILITY
-- Query : Checking table if it is loading correctly and if the data is ready for use
select * 
from `workspace`.`default`.`coffee_case_study` limit 1000;
----------------------------------------------------------------------------------------------------------------------------------------------------------------------Query . Checking Store location and number of products sold per each store
Select store_location,
       product_category,
       product_type
From  `workspace`.`default`.`coffee_case_study`;  

----------------------------------------------------------------------------------------------------------------------------------------------------------------
---Query 1 DATA CLEANING & TRANSFORMATION
--Standardize unit_price (replace commas and cast to decimal)
SELECT transaction_id,
       transaction_date,
       transaction_time,
      product_category,
      product_detail,
      CAST(REPLACE(unit_price, ',', '.') AS DECIMAL(10,2)) AS unit_price_clean,
      transaction_qty
FROM `workspace`.`default`.`coffee_case_study`;


----------------------------------------------------------------------------------------------------------------------------------------------------------------
---Query 2: Running the KPI METRICS
---Calculating the Total Amount generated by the Coffee Shop for the whole Selling period

SELECT SUM(transaction_qty * unit_price) AS total_revenue
FROM `workspace`.`default`.`coffee_case_study`;

---Calculating total Orders 

SELECT COUNT(DISTINCT transaction_id) AS total_orders
FROM `workspace`.`default`.`coffee_case_study`;

---Calculating  Average Order Value

SELECT SUM(transaction_qty * unit_price) / COUNT(DISTINCT transaction_id) AS avg_order_value
FROM `workspace`.`default`.`coffee_case_study`;

----------------------------------------------------------------------------------------------------------------------------------------------------------------

----3. OVERAL PRODUCT PERFORMANCE 
---Calculating Revenue by Product Category
SELECT 
    product_category,
    SUM(transaction_qty * unit_price) AS revenue
FROM `workspace`.`default`.`coffee_case_study`
GROUP BY product_category
ORDER BY revenue DESC;

----------------------------------------------------------------------------------------------------------------------------------------------------------------
---Query 4: Indicating  High-performing and low-performing products
------ Top 5 Best-Selling Products
SELECT 
    product_detail,
    SUM(transaction_qty) AS total_quantity,
    SUM(transaction_qty * unit_price) AS revenue
FROM `workspace`.`default`.`coffee_case_study`
GROUP BY product_detail
ORDER BY total_quantity DESC
LIMIT 5;

----- Bottom 5 Products
SELECT 
    product_detail,
    SUM(transaction_qty) AS total_quantity
FROM `workspace`.`default`.`coffee_case_study`
GROUP BY product_detail
ORDER BY total_quantity ASC
LIMIT 5;

----------------------------------------------------------------------------------------------------------------------------------------------------------------
---Query 4: TIME-BASED ANALYSIS
---Calculation of Revenue by Hour (Peak Time Analysis)
SELECT 
    EXTRACT(HOUR FROM transaction_time) AS hour,
    SUM(transaction_qty * unit_price) AS revenue
FROM `workspace`.`default`.`coffee_case_study`
GROUP BY hour
ORDER BY hour;

--- Calculating Revenue by Day (Trend Analysis)
SELECT 
    transaction_date,
    SUM(transaction_qty * unit_price) AS daily_revenue
FROM `workspace`.`default`.`coffee_case_study`
GROUP BY transaction_date
ORDER BY transaction_date;

---Calculation  Revenue by Day of Week
SELECT 
    DAYNAME(transaction_date) AS day_of_week,
    SUM(transaction_qty * unit_price) AS revenue
FROM `workspace`.`default`.`coffee_case_study`
GROUP BY day_of_week
ORDER BY revenue DESC;

---- Calculating -- Revenue by Day of Month
SELECT 
    MONTHNAME(transaction_date) AS day_of_week,
    SUM(transaction_qty * unit_price) AS revenue
FROM `workspace`.`default`.`coffee_case_study`
GROUP BY day_of_week
ORDER BY revenue DESC;

----------------------------------------------------------------------------------------------------------------------------------------------------------------
---Query 5: SALES DISTRIBUTION
--Calculating Quantity Sold by Product Category
SELECT 
    product_category,
    SUM(transaction_qty) AS total_quantity
FROM `workspace`.`default`.`coffee_case_study`
GROUP BY product_category
ORDER BY total_quantity DESC;

---- Calculating Total units sold by product type or detail
SELECT 
    product_type,
    SUM(transaction_qty) AS total_quantity
FROM `workspace`.`default`.`coffee_case_study`
GROUP BY product_type
ORDER BY total_quantity DESC;

----------------------------------------------------------------------------------------------------------------------------------------------------------------

---Query 6: Grouping by 30-minute time intervals
---Calculating Units sold and generated Revenue per 30 minute time_bucket
SELECT 
    transaction_time_bucket,
    SUM(transaction_qty) AS total_units_sold,
    SUM(transaction_qty * unit_price) AS total_revenue
FROM (
    SELECT *,
           CONCAT(
               DATE_FORMAT(transaction_time, 'yyyy-MM-dd HH:'),
               LPAD(FLOOR(MINUTE(transaction_time)/30)*30, 2, '0')
           ) AS transaction_time_bucket
    FROM `workspace`.`default`.`coffee_case_study`
) 
GROUP BY transaction_time_bucket
ORDER BY transaction_time_bucket
LIMIT 20;

----Query 7. Cacluating  Total Units sold and Revenue generated By Grouping Product_types per time_buckets
SELECT 
    product_type,
    transaction_time_bucket,
    SUM( transaction_qty) AS total_units_sold,
    SUM( transaction_qty * unit_price) AS total_revenue
FROM (
    SELECT 
        product_type,
        transaction_qty,
        unit_price,
        CONCAT(
            DATE_FORMAT(transaction_time, 'yyyy-MM-dd HH:'),
            LPAD(FLOOR(MINUTE(transaction_time)/30)*30, 2, '0')
        ) AS transaction_time_bucket
    FROM `workspace`.`default`.`coffee_case_study`
) 
GROUP BY product_type, transaction_time_bucket
ORDER BY product_type, transaction_time_bucket;

----------------------------------------------------------------------------------------------------------------------------------------------------------------

---8. Summary of Stats
SELECT 
    COUNT(*) AS number_of_rows, 
    COUNT(DISTINCT transaction_id) AS number_of_sales, 
    COUNT(DISTINCT product_id) AS number_of_products, 
    COUNT(DISTINCT store_id) AS number_of_stores 
FROM `workspace`.`default`.`coffee_case_study`;

----------------------------------------------------------------------------------------------------------------------------------------------------------------
---Checking Revenue by Day and Month
SELECT 
    transaction_id, 
    transaction_date, 
    Dayname(transaction_date) AS Day_name, 
    Monthname(transaction_date) AS Month_name, 
    transaction_qty*unit_price AS revenue_per_tnx 
FROM `workspace`.`default`.`coffee_case_study`;

----------------------------------------------------------------------------------------------------------------------------------------------------------------

----9. Daily sales stats
SELECT 
    transaction_date, 
    Dayname(transaction_date) AS Day_name, 
    Monthname(transaction_date) AS Month_name, 
    COUNT(DISTINCT transaction_id) AS Number_of_sales, 
    SUM(transaction_qty*unit_price) AS revenue_per_day 
FROM `workspace`.`default`.`coffee_case_study`
GROUP BY transaction_date, Day_name, Month_name;

------------------------------------------------------------------------------------------------------------------------------------------------------------------
---Time of day store performs best
SELECT 
    CASE 
        WHEN EXTRACT(HOUR FROM transaction_time) BETWEEN 6 AND 11 THEN 'Morning'
        WHEN EXTRACT(HOUR FROM transaction_time) BETWEEN 12 AND 16 THEN 'Afternoon'
        WHEN EXTRACT(HOUR FROM transaction_time) BETWEEN 17 AND 20 THEN 'Evening'
        ELSE 'Night'
    END AS time_of_day,

    COUNT(transaction_id) AS total_transactions,
    SUM(transaction_qty) AS total_units_sold,
    SUM(transaction_qty * unit_price) AS total_revenue

FROM `workspace`.`default`.`coffee_case_study`
GROUP BY time_of_day
ORDER BY total_revenue DESC;

----------------------------------------------------------------------------------------------------------------------------------------------------------------

---10. Combining functions to get a clean and enhanced data set
 SELECT 
        transaction_id,
        transaction_date,
        transaction_time,
        transaction_qty,
        store_id,
        store_location,
        product_id,
        unit_price,
        product_category,
        product_type,
       product_detail,
---Adding columns to enhance the table for better insights
---Adding new column 1
      Dayname(transaction_date) AS Day_name,
---Adding new column 2
      Monthname(transaction_date) AS Month_name,
---Adding new column 3
      Dayofmonth(transaction_date) AS Date_of_month,
---Adding new column 4- Showing weekedday/Weekend
  CASE
     WHEN Dayname(transaction_date) IN ('Sun', 'Sat') THEN 'Weekend'
   ELSE 'Weekday'
   END AS Day_classification,
---Adding new column 5 (Time buckets)
CASE
    WHEN Date_format (transaction_time, 'HH:mm:ss') BETWEEN '05:00:00' AND '08:59:59' THEN 'Morning_Rush'
     WHEN Date_format (transaction_time, 'HH:mm:ss') BETWEEN '09:00:00' AND '11:59:59' THEN 'Mid_Morning'
     WHEN Date_format (transaction_time, 'HH:mm:ss') BETWEEN '12:00:00' AND '16:59:59' THEN 'Afternoon'
      WHEN Date_format (transaction_time, 'HH:mm:ss') BETWEEN '17:00:00' AND '19:59:59' THEN 'Rush_Hour'
    ELSE 'Night'
END AS  Time_classification,
---Adding new column 6 (Spend buckets)
CASE
    WHEN (transaction_qty*unit_price) <=50 THEN '01.Low_Spender'
    WHEN (transaction_qty*unit_price) BETWEEN 51 AND 200 THEN '02.Medium_Spender'
    WHEN (transaction_qty*unit_price) BETWEEN 201 AND 300 THEN '03.Squander' 
    ELSE '04. Blesser'
    END AS  Spend_Bucktet,
---Adding new column 7 (Revenue)
    transaction_qty*unit_price AS Revenue
From `workspace`.`default`.`coffee_case_study`;
